version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: mysecretpassword # senha para teste
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      # conexão com o banco
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres # referencia o nome do serviço 'postgres' acima
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: mysecretpassword

      # desativa o login para facilitar o teste local
      N8N_BASIC_AUTH_ACTIVE: "false"
      
      TZ: 'America/Sao_Paulo' # fuso-horário para os logs
    ports:
      - "5678:5678"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      # mapeia nosso node customizado (compilado) para dentro do container
      - ./dist:/home/node/.n8n/custom
      # volume para salvar os workflows e dados do n8n
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local